version: "3.9"
networks:
  backend-net:
services:
  # scylla:
  #   image: scylladb/scylla:5.1.8
  #   container_name: scylla
  #   hostname: scylla
  #   networks:
  #     - backend-net
  #   volumes:
  #     - ./db:/var/lib/scylla:rw
  #
  http-api:
    image: http-api:latest
    container_name: http-api
    hostname: http-api
    networks:
      - backend-net
    ports:
      - 8080:8080
    environment: &http_env
      - MIDDLEWARE_URI=http://grpc-db:8081

  grpc-db:
    image: grpc-db:latest
    container_name: grpc-db 
    hostname: grpc-db 
    networks:
      - backend-net
    restart: always
    environment: &middleware_env
      - API_URI=http://http-api:8080

  nginx:
    image: nginx:latest
    container_name: nginx 
    hostname: nginx 
    networks:
      - backend-net
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
