version: "3.9"
networks:
  backend-net:
services:

  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    hostname: scylla
    networks:
      - backend-net
    ports:
      - 9042:9042
    volumes:
      - ./db:/var/lib/scylla:rw

    # This is used to have grpc-db start after healthcheck is successful
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 20

  http-api:
    image: cbui125/http-api:0.1.1
    container_name: http-api
    hostname: http-api
    networks:
      - backend-net
    # ports:
    #   - 8080:8080
    environment:
      - MIDDLEWARE_URI=http://grpc-db:8081
      - RUST_LOG=DEBUG

  grpc-db:
    image: cbui125/grpc-db:0.1.1
    container_name: grpc-db 
    hostname: grpc-db 
    networks:
      - backend-net
    restart: always
    environment:
      - RUST_LOG=DEBUG
      - API_URI=http://http-api:8080
      - IS_LOCAL_DEV=true
    depends_on:
      scylla:
          condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx 
    hostname: nginx 
    networks:
      - backend-net
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
